{
 "title": "System Processes Metrics",
 "description": "Show Linux Process information as captured by \n https://github.com/ncabatoff/process-exporter  designed for PMM",
 "tags": [ "Insight" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values({job=\"mydev\"},instance)"
    }
   },
   {
    "name": "groupname",
    "query": {
     "query": "label_values({instance=\"$instance\"},groupname)"
    }
   },
   {
    "name": "mode",
    "query": {
     "query": "label_values({instance=\"$instance\"},mode)"
    }
   },
   {
    "name": "memtype",
    "query": {
     "query": "label_values({instance=\"$instance\"},memtype)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Process Uptime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "targets": [
    {}
   ]
  },
  {
   "title": "Processes by uptime",
   "type": "state-timeline",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "(namedprocess_namegroup_oldest_start_time_seconds{instance=\"$instance\", groupname=~\"$groupname\"} > (time() - 86400)) * 1000",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top processes by Total CPU cores used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(5, (rate(namedprocess_namegroup_cpu_seconds_total{instance=\"$instance\", groupname=~\"$groupname\", mode=~\"$mode\"}[$__rate_interval])))",
     "legendFormat": "{{groupname}}-{{mode}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Top processes by Total CPU cores used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(5, (rate(namedprocess_namegroup_cpu_seconds_total{instance=\"$instance\", groupname=~\"$groupname\", mode=\"system\"}[$__rate_interval])))",
     "legendFormat": "{{groupname}}-{{mode}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top processes by Used  memory[swapped,resident]",
   "type": "timeseries",
   "description": "Memory Used by Processes, counted as Resident Memory + Space used in Swap Space",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, avg_over_time(namedprocess_namegroup_memory_bytes{instance=\"$instance\", groupname=~\"$groupname\", memtype=\"swapped\"}[$__interval]) + ignoring(memtype) avg_over_time(namedprocess_namegroup_memory_bytes{instance=\"$instance\", groupname=~\"$groupname\", memtype=\"resident\"}[$__interval]))",
     "legendFormat": "{{groupname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Top processes by Resident memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, avg_over_time(namedprocess_namegroup_memory_bytes{instance=\"$instance\", groupname=~\"$groupname\", memtype=\"resident\"}[$__interval]))",
     "legendFormat": "{{groupname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Top processes by Virtual memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, avg_over_time(namedprocess_namegroup_memory_bytes{instance=\"$instance\", groupname=~\"$groupname\", memtype=\"virtual\"}[$__interval]))",
     "legendFormat": "{{groupname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Top processes by Swapped memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(5, avg_over_time(namedprocess_namegroup_memory_bytes{instance=\"$instance\", groupname=~\"$groupname\", memtype=\"swapped\"}[$__interval]))",
     "legendFormat": "{{groupname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Process Disk IO Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top processes by Bytes Written",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(5, rate(namedprocess_namegroup_write_bytes_total{instance=\"$instance\", groupname=~\"$groupname\"}[$__rate_interval]))",
     "legendFormat": "{{groupname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Top processes by Bytes Written",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(5, rate(namedprocess_namegroup_write_bytes_total{instance=\"$instance\", groupname=~\"$groupname\"}[$__rate_interval]))",
     "legendFormat": "{{groupname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Process and Thread Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top processes by number of  processes instances",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, max_over_time(namedprocess_namegroup_num_procs{instance=\"$instance\", groupname=~\"$groupname\"}[$__interval]))",
     "legendFormat": "{{groupname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Top processes by number of  processes instances",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, max_over_time(namedprocess_namegroup_num_procs{instance=\"$instance\", groupname=~\"$groupname\"}[$__interval]))",
     "legendFormat": "{{groupname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Process Context Switches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top Processes by Voluntary Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, rate(namedprocess_namegroup_context_switches_total{instance=\"$instance\", groupname=~\"$groupname\",ctxswitchtype=\"voluntary\"}[$__rate_interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top Processes by Voluntary Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, rate(namedprocess_namegroup_context_switches_total{instance=\"$instance\", groupname=~\"$groupname\",ctxswitchtype=\"voluntary\"}[$__rate_interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Process File Descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top processes by Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, max_over_time(namedprocess_namegroup_open_filedesc{instance=\"$instance\", groupname=~\"$groupname\"}[$__interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by File Descriptor Usage Percent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(5, max_over_time(namedprocess_namegroup_worst_fd_ratio{instance=\"$instance\", groupname=~\"$groupname\"}[$__interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Process Page Faults",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top processes by Major Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, rate(namedprocess_namegroup_major_page_faults_total{instance=\"$instance\", groupname=~\"$groupname\"}[$__rate_interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top processes by Minor Page Faults",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(5, rate(namedprocess_namegroup_minor_page_faults_total{instance=\"$instance\", groupname=~\"$groupname\"}[$__rate_interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Process Statuses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Top running processes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, max_over_time(namedprocess_namegroup_states{instance=\"$instance\", groupname=~\"$groupname\", state=\"Running\"}[$__interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Top of processes waiting on IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5, max_over_time(namedprocess_namegroup_states{instance=\"$instance\", groupname=~\"$groupname\", state=\"Waiting\"}[$__interval]))",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Process Kernel Waits (WCHAN)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Kernel waits for $groupname",
   "type": "timeseries",
   "description": "- **do_poll**: 等待 I/O 操作的完成，通常用于检测文件描述符的状态变化。\n- **futex_wait_queue**: 线程正在等待一个快速用户空间互斥量（futex）条件，通常用于实现线程间的高效等待。\n- **ep_poll**: 线程正在等待事件的发生，通常与 `epoll` 系统调用关联，用于高效监控文件描述符状态变化。\n- **do_select**: 等待一个或多个文件描述符的状态变化，类似于 `poll` 系统调用。\n- **do_wait**: 线程正在等待子进程结束，通常用于父进程等待子进程完成执行。\n- **hrtimer_nanosleep**: 线程因高精度定时器而休眠，通常涉及短时间的延迟。\n- **wait_woken**: 线程正在等待被其他线程唤醒，通常与条件变量或信号量相关。\n- **syslog_print**: 线程正在等待打印日志，这可能是由于日志服务繁忙或等待 I/O 完成。",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5,sum(avg_over_time(namedprocess_namegroup_threads_wchan{instance=\"$instance\", groupname=~\"$groupname\"}[$__interval])) by (wchan) )",
     "legendFormat": "{{groupname}}"
    }
   ]
  },
  {
   "title": "Kernel wait Details for $groupname",
   "type": "timeseries",
   "description": "- **do_poll**: 等待 I/O 操作的完成，通常用于检测文件描述符的状态变化。\n- **futex_wait_queue**: 线程正在等待一个快速用户空间互斥量（futex）条件，通常用于实现线程间的高效等待。\n- **ep_poll**: 线程正在等待事件的发生，通常与 `epoll` 系统调用关联，用于高效监控文件描述符状态变化。\n- **do_select**: 等待一个或多个文件描述符的状态变化，类似于 `poll` 系统调用。\n- **do_wait**: 线程正在等待子进程结束，通常用于父进程等待子进程完成执行。\n- **hrtimer_nanosleep**: 线程因高精度定时器而休眠，通常涉及短时间的延迟。\n- **wait_woken**: 线程正在等待被其他线程唤醒，通常与条件变量或信号量相关。\n- **syslog_print**: 线程正在等待打印日志，这可能是由于日志服务繁忙或等待 I/O 完成。",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(5,sum(avg_over_time(namedprocess_namegroup_threads_wchan{instance=\"$instance\", groupname=~\"$groupname\"}[$__interval])) by (wchan,groupname) )",
     "legendFormat": "{{groupname}}"
    }
   ]
  }
 ]
}