{
 "title": "Trino",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values({job=~\"$job\"},instance)"
    }
   },
   {
    "name": "memarea",
    "query": {
     "query": "label_values({job=~\"$job\", instance=\"$instance\"},area)"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "label_values({job=\"$job\", instance=~\"$instance\"},pool)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Base", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Restart-times",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=~\"$job\"} * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(trino_execution_QueryManager_SubmittedQueries_TotalCount{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "SubmittedQueries"
    },
    {
     "expr": "trino_execution_QueryManager_RunningQueries{job=~\"$job\"}",
     "legendFormat": "RunningQueries"
    },
    {
     "expr": "trino_execution_QueryManager_QueuedQueries{job=~\"$job\"}",
     "legendFormat": "QueuedQueries"
    },
    {
     "expr": "increase(trino_execution_QueryManager_StartedQueries_TotalCount{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "StartedQueries"
    },
    {
     "expr": "increase(trino_execution_QueryManager_CompletedQueries_TotalCount{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "CompletedQueries"
    },
    {
     "expr": "increase(trino_execution_QueryManager_CanceledQueries_TotalCount{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "CanceledQueries"
    },
    {
     "expr": "increase(trino_execution_QueryManager_FailedQueries_TotalCount{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "FailedQueries"
    },
    {
     "expr": "increase(trino_execution_QueryManager_UserErrorFailures_TotalCount{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "UserErrorFailures"
    },
    {
     "expr": "increase(trino_execution_QueryManager_AbandonedQueries_TotalCount{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "AbandonedQueries"
    },
    {
     "expr": "increase(trino_execution_QueryManager_InternalFailures_TotalCount{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "InternalFailures"
    },
    {
     "expr": "increase(trino_execution_QueryManager_ExternalFailures_TotalCount{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "ExternalFailures"
    },
    {
     "expr": "increase(trino_execution_QueryManager_InsufficientResourcesFailures_TotalCount{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "InsufficientResourcesFailures"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ConsumedInput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(trino_execution_QueryManager_ConsumedInputBytes_TotalCount{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "ConsumedInputBytes"
    },
    {
     "expr": "increase(trino_execution_QueryManager_ConsumedInputRows_TotalCount{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "ConsumedInputRows"
    }
   ]
  },
  {
   "title": "ExecutionTime",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "trino_execution_QueryManager_ExecutionTime_OneMinute_Avg{job=~\"$job\"}",
     "legendFormat": "OneMinute_Avg"
    },
    {
     "expr": "trino_execution_QueryManager_ExecutionTime_OneMinute_Max{job=~\"$job\"}",
     "legendFormat": "OneMinute_Max"
    }
   ]
  },
  {
   "title": "常驻内存",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MemoryHeapCommitted",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{job=~\"$job\", area=\"heap\"}",
     "legendFormat": "MemoryHeapCommitted-{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "MemoryHeapRate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=~\"$job\", area=\"heap\"} / jvm_memory_bytes_committed{job=~\"$job\", area=\"heap\"}",
     "legendFormat": "MemoryHeapRate-{{instance}}"
    }
   ]
  },
  { "title": "Info-$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 }, "repeat": "instance" },
  {
   "title": "uptime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "uptimes",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(process_start_time_seconds{job=~\"$job\", instance=~\"$instance\"}[$__range])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Restart-times",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 13, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=~\"$job\", instance=~\"$instance\"} * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(trino_execution_QueryManager_SubmittedQueries_TotalCount{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "SubmittedQueries"
    },
    {
     "expr": "increase(trino_execution_QueryManager_StartedQueries_TotalCount{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "StartedQueries"
    },
    {
     "expr": "increase(trino_execution_QueryManager_AbandonedQueries_TotalCount{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "AbandonedQueries"
    },
    {
     "expr": "trino_execution_QueryManager_QueuedQueries{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "QueuedQueries"
    },
    {
     "expr": "trino_execution_QueryManager_RunningQueries{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "RunningQueries"
    },
    {
     "expr": "increase(trino_execution_QueryManager_CompletedQueries_TotalCount{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "CompletedQueries"
    },
    {
     "expr": "increase(trino_execution_QueryManager_FailedQueries_TotalCount{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "FailedQueries"
    },
    {
     "expr": "increase(trino_execution_QueryManager_CanceledQueries_TotalCount{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "CanceledQueries"
    },
    {
     "expr": "increase(trino_execution_QueryManager_UserErrorFailures_TotalCount{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "UserErrorFailures"
    },
    {
     "expr": "increase(trino_execution_QueryManager_ExternalFailures_TotalCount{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ExternalFailures"
    },
    {
     "expr": "increase(trino_execution_QueryManager_InternalFailures_TotalCount{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "InternalFailures"
    },
    {
     "expr": "increase(trino_execution_QueryManager_InsufficientResourcesFailures_TotalCount{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "InsufficientResourcesFailures"
    }
   ]
  },
  {
   "title": "TaskExecutor",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trino_execution_executor_TaskExecutor_Tasks{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Tasks"
    },
    {
     "expr": "trino_execution_executor_TaskExecutor_ProcessorExecutor_QueuedTaskCount{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "QueuedTask"
    },
    {
     "expr": "trino_execution_executor_TaskExecutor_TotalSplits{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "TotalSplits"
    },
    {
     "expr": "trino_execution_executor_TaskExecutor_RunningSplits{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "RunningSplits"
    },
    {
     "expr": "trino_execution_executor_TaskExecutor_BlockedSplits{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "BlockedSplits"
    },
    {
     "expr": "trino_execution_executor_TaskExecutor_WaitingSplits{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "WaitingSplits"
    }
   ]
  },
  {
   "title": "Pool Committed",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_committed{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Pool Used",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "MemoryHeapCommittedRate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{job=~\"$job\", area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "HeapCommitted"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{job=~\"$job\", instance=~\"$instance\", pool=~\"$pool\"})\r\n/ sum (jvm_memory_bytes_committed{job=~\"$job\", area=\"heap\", instance=~\"$instance\"})\r\n",
     "legendFormat": "PoolCommittedRateAll"
    },
    {
     "expr": "sum by (pool) (jvm_memory_pool_bytes_committed{job=~\"$job\", instance=~\"$instance\", pool=~\"$pool\"})\r\n/ ignoring(pool) group_left sum (jvm_memory_bytes_committed{job=~\"$job\", area=\"heap\", instance=~\"$instance\"})\r\n",
     "legendFormat": "PoolCommittedRate-{{pool}}"
    }
   ]
  },
  {
   "title": "MemoryPoolUsedRate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{job=~\"$job\", area=\"heap\", instance=~\"$instance\"}",
     "legendFormat": "HeapCommitted"
    },
    {
     "expr": "sum(jvm_memory_pool_bytes_used{job=~\"$job\", instance=~\"$instance\", pool=~\"$pool\"})\r\n/ sum (jvm_memory_bytes_committed{job=~\"$job\", area=\"heap\", instance=~\"$instance\"})\r\n",
     "legendFormat": "PoolUsedRateAll"
    },
    {
     "expr": "sum by (pool) (jvm_memory_pool_bytes_used{job=~\"$job\", instance=~\"$instance\", pool=~\"$pool\"})\r\n/ ignoring(pool) group_left sum (jvm_memory_bytes_committed{job=~\"$job\", area=\"heap\", instance=~\"$instance\"})\r\n",
     "legendFormat": "PoolUsedRate-{{pool}}"
    }
   ]
  },
  {
   "title": "GC Times",
   "type": "timeseries",
   "description": "- `gc=\"PS MarkSweep\"`：表明PS MarkSweep（老年代垃圾收集器）。\n\n- `gc=\"PS Scavenge\"`：表明PS Scavenge（新生代垃圾收集器）。",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "timeseries",
   "description": "- `gc=\"PS MarkSweep\"`：表明PS MarkSweep（老年代垃圾收集器）。\n\n- `gc=\"PS Scavenge\"`：表明PS Scavenge（新生代垃圾收集器）。",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_current{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_deadlocked{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "deadlocked"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_threads_state{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "OS Memory",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_TotalPhysicalMemorySize{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "TotalPhysicalMemorySize"
    },
    {
     "expr": "java_lang_OperatingSystem_TotalMemorySize{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "TotalMemorySize"
    },
    {
     "expr": "java_lang_OperatingSystem_CommittedVirtualMemorySize{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "CommittedVirtualMemorySize"
    },
    {
     "expr": "java_lang_OperatingSystem_FreePhysicalMemorySize{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "FreePhysicalMemorySize"
    },
    {
     "expr": "java_lang_OperatingSystem_FreeMemorySize{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "FreeMemorySize"
    }
   ]
  },
  {
   "title": "OS CPU",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max_over_time(java_lang_OperatingSystem_SystemCpuLoad{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "SystemCpuLoad"
    },
    {
     "expr": "max_over_time(java_lang_OperatingSystem_CpuLoad{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "CpuLoad"
    },
    {
     "expr": "max_over_time(java_lang_OperatingSystem_ProcessCpuLoad{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "ProcessCpuLoad"
    }
   ]
  }
 ]
}